### ISSUE TITLE
Please add demo for Decompression from LZMA

### ISSUE THREAD

**Issue by piker00** [ccy/delphi-zip#1]
Please add demo for Decompression from LZMA, thanks.

**Comment by Ze2QvoQxxKeu** [comment]
procedure LZMAcompress(InStream, OutStream: TStream);
    var
      Encoder: TLZMAEncoderStream;
    begin
      Encoder := TLZMAEncoderStream.Create(OutStream, nil);
      try
        Encoder.Write(InStream, InStream.Size);
      finally
        FreeAndNil(Encoder);
      end;
    end;
    
    procedure LZMAdecompress(InStream, OutStream: TStream);
    const
      BufferSize = 1024 * 64;
    var
      Decoder: TLZMADecoderStream;
      Buffer: TBytes;
      BytesRead, Offset: Integer;
    begin
      Decoder := TLZMADecoderStream.Create(InStream, nil);
      try
        SetLength(Buffer, BufferSize);
        Offset := 0;
        repeat
          BytesRead := Decoder.Read(Buffer, Offset, BufferSize);
          OutStream.Write(Buffer, BytesRead);
          Inc(Offset, BytesRead);
        until BytesRead < BufferSize;
      finally
        FreeAndNil(Decoder);
        Finalize(Buffer);
      end;
    end;

**Comment by ccy** [comment]
Please refer to [test case](https://github.com/ccy/delphi-zip/blob/XE4/System.Zip.TestCase.pas).
