### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by ElSanchez666** [ccy/delphi-zip#10]
Hi.

1. Constants SZipExceedNumberOfFiles and SSpecifiedFileNotFound not declared in implementation section.
2. Memory leak in TZipFile.GetEncoding. Just free FCP437Encoding in class destructor.

**Comment by ccy** [comment]
Memory leak `FCP437Encoding` fixed in [RAD Studio 10.4](https://github.com/ccy/delphi-zip/tree/RAD10.4)
