### ISSUE TITLE
Position in OnProgress resets sometimes at lage files

### ISSUE THREAD

**Issue by realcolaflasche** [ccy/delphi-zip#11]
In the TZipFile.OnProgress-Event the Position resets sometimes.
I have a 12 GB File and was at position 4,294,770,688 of 13,123,635,712. After that again at 819,200 / 13,123,635,712.

Regards

**Comment by ccy** [comment]
I believe this should have solved in RAD Studio 11.  So does `System.Zip2.pas` since branch [RAD11](https://github.com/ccy/delphi-zip/tree/RAD11)
