### ISSUE TITLE
decompressing a file larger than 4G, position error!

### ISSUE THREAD

**Issue by cmd9x** [ccy/delphi-zip#14]
When decompressing a file larger than 4G and the progress is 4G Size, Position starts from the beginning. It is suspected that the bug in System.ZLib.pas exists in RAD11.

**Comment by ccy** [comment]
I have tested in RAD Studio 11 and it work as expected.  So does `System.Zip2.pas` since branch [RAD11](https://github.com/ccy/delphi-zip/tree/RAD11)
