### ISSUE TITLE
TZipFile Comment

### ISSUE THREAD

**Issue by David-Nardi** [ccy/delphi-zip#16]
I have reported (and solve) an issue to Embarcadero : [RSP-37093](https://quality.embarcadero.com/browse/RSP-37093)

You can download System.Zip2 corrected in [TestZipFIle](http://david.nardi.free.fr/bug/TestZipFile.zip)

There is a small projet to demonstrate the bug.

Best regards,
David Nardi

**Comment by ccy** [comment]
@David-Nardi , after you clone the repository.  You may use `git submodule update --init` to pull `lzmadsk` module.

**Comment by ccy** [comment]
For [RSP-37093](https://quality.embarcadero.com/browse/RSP-37093), I think I have to wait for Embarcadero to solve it.
