### ISSUE TITLE
Use a patch file instead of publishing copyrighted code

### ISSUE THREAD

**Issue by darianmiller** [ccy/delphi-zip#18]
The code provided System.Zip2.pas is copyrighted code from Embarcadero. You should not be publishing their code, you should provide a patch file instead.

**Comment by ccy** [comment]
Noted.  The LZMA compression handler has registered to System.Zip.pas using [detour](https://github.com/ccy/delphi-detours-library) patch strategy start from commit 8eb26f5d5236b63fe1021ddc41f986610b2ddc24
