### ISSUE TITLE
Cannot open this ZIP64 archive: SZipInvalidCentralHeader

### ISSUE THREAD

**Issue by tueddy** [ccy/delphi-zip#2]
Hi,

i get an error "ZipInvalidCentralHeader" opening this OPC-file:
https://github.com/3MFConsortium/lib3mf/blob/master/TestFiles/3mfbase8_VertexTet1.3mf

More testfiles (some are ZIP64) here:
https://github.com/3MFConsortium/lib3mf/blob/master/TestFiles

Best regards
Dirk
[3mfbase8_VertexTet1.zip](https://github.com/ccy/delphi-zip/files/1006969/3mfbase8_VertexTet1.zip)

**Comment by tueddy** [comment]
Hello i have to push it ;-)
Can you reproduce the issue? Is delphi-zip capable to open ZIP64 arcihives?
Thanks in advance
Dirk

**Comment by ccy** [comment]
Yes, I can replay. I am investigating.

**Comment by tueddy** [comment]
Any news or workaround here?
Kind regards
Dirk

**Comment by ccy** [comment]
Can you try with latest [RAD11](https://github.com/ccy/delphi-zip/tree/RAD11) branch that has reverted to RAD Studio implementation for Zip64 support.
