### ISSUE TITLE
not support zip files to a TStream

### ISSUE THREAD

**Issue by wang80919** [ccy/delphi-zip#5]
i want create a zip file in memory.
i do not want creat a real file.

**Comment by ccy** [comment]
Refer to [Delphi’s TZipFile working on a stream](https://blog.dummzeuch.de/2020/08/20/delphis-tzipfile-working-on-a-stream/) for more information.

**Comment by wang80919** [comment]
thanks 
but this is a year 2017 's  bug.
Later, I changed to 7z.dll ,call it by delphi(SevenZip.pas).
