### ISSUE TITLE
Zip more than 65535 files

### ISSUE THREAD

**Issue by yann-papouin** [ccy/delphi-zip#9]
I know that you are not the one that wrote this part but do you know why there is an hard-coded file limit in System.Zip.pas ? I'm not able to find a reference a out this limit on Internet.

```
  if FFiles.Count = $FFFF then
    raise EZipException.CreateRes(@SZipExceedNumberOfFiles);
```

**Comment by ccy** [comment]
`System.Zip.pas` has removed the restriction since RAD Studio 11.  So does `System.Zip2.pas` since branch [RAD11](https://github.com/ccy/delphi-zip/tree/RAD11)
